### ISSUE TITLE
"invalid equation" in README.md

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [masa-su/pixyz#111]
![スクリーンショット 2020-03-12 5 01 47](https://user-images.githubusercontent.com/990923/76458990-c4192480-641e-11ea-90bf-fc7c6b4a6a49.png)
README.md の中の数式の一部（変分事後分布の式）が表示されなくなっていました.

**Comment by masa-su** [comment]
@tanaka-hiroki1989 
ご指摘ありがとうございます．こちら修正しましたので，再度ご確認ください．
