### ISSUE TITLE
Add Arxiv paper link to readme

### ISSUE THREAD

**Issue by impredicative** [masa-su/pixyz#52]
Thanks for this code. For reference purposes, can you please mention and add a link to your corresponding Arxiv paper to the readme? I assume it is https://arxiv.org/abs/1611.01891

**Comment by masa-su** [comment]
Thank you for seeing our library!
I'd like to confirm which do you want to reference, this library (Pixyz) or JMVAE paper (https://arxiv.org/abs/1611.01891)?

In the case of JMVAE, please also check the original implementation of this arXiv paper in the following repo. 
https://github.com/masa-su/jmvae
There is a link (and BibTeX) to this paper in the readme here.

In the case of Pixyz, we've not yet published a paper of this, so we can't provide a way to reference (such as BibTeX) for now.

Also, please note that this library is not limited to JMVAE. You can implement various deep generative models with Pixyz, so I'll not add only a link to the JMVAE paper to this readme. Instead, I added this link in the notebook of JMVAE's example. 
https://github.com/masa-su/pixyz/blob/master/examples/jmvae.ipynb

Thank you.
