### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by cross32768** [masa-su/pixyz#82]
In the "Quick Start" section in README.md
```python3
>>> prior = Normal(loc=torch.tensor(0.), scale=torch.tensor(1.),
...                var=["z"], features_dim=[64], name="p_prior")
```

There is no attribute "features_dim" in the "Normal" class.
Is this a mistake of "features_shape"?

**Comment by masa-su** [comment]
@cross32768
Yes. This was a typo as you pointed out, so I fixed it. 
Thank you for letting us know!
